export const LOAD_AUTH_SUCCESS = 'LOAD_AUTH_SUCCESS';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const LOAD_SECRETS = 'LOAD_SECRETS';
export const LOAD_SECRETS_SUCCESS = 'LOAD_SECRETS_SUCCESS';
export const LOAD_SECRETS_FAILURE = 'LOAD_SECRETS_FAILURE';
