export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const SECRETS_LOAD_REQUEST = 'SECRETS_LOAD_REQUEST';
export const SECRETS_LOAD_SUCCESS = 'SECRETS_LOAD_SUCCESS';
export const SECRETS_LOAD_FAILURE = 'SECRETS_LOAD_FAILURE';
